# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-22 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('cast', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=256)),
                ('food', models.CharField(max_length=256)),
                ('animal', models.CharField(max_length=256)),
            ],
        ),
    ]
